main : com.clashwars.dvz.DvZ
name: DvZ
version: 0.1
description: Dwarves VS Zombies plugin.
depend: [CWCore,ClashWars,CWStats]
commands:
  dvz:
    description: Main dvz command
    usage: /<command>
    aliases: [d, dz, dvsz]
  storage:
    description: Virtual storage for VIP members.
    usage: /<command>
    aliases: [chests, chest]
  furnace:
    description: Virtual furnace for VIP members.
    usage: /<command>
    aliases: [furnaces, smelt, cook]
  enchant:
    description: Virtual enchanting for VIP members.
    usage: /<command>
    aliases: [enchanting]
  disposal:
    description: Virtual item disposal.
    usage: /<command>
    aliases: [dispose,clear]
  settings:
    description: View and manage settings.
    usage: /<command>
    aliases: [prefs]