main : com.clashwars.dvz.DvZ
name: DvZ
version: 0.1
description: Dwarves VS Zombies plugin.
depend: [CWCore]
commands:
  dvz:
    description: Main dvz command
    usage: /<command>
    aliases: [d, dz, dvsz]
  cow:
    description: /cow
    usage: /<command>