main : com.clashwars.dvz.DvZ
name: DvZ
version: 0.1
description: Dwarves VS Zombies plugin.
depend: [CWCore]
commands:
  dvz:
    description: Main dvz command
    usage: /<command>
    aliases: [d, dz, dvsz]
  cow:
    description: /cow
    usage: /<command>
  soundtest:
    description: Command to test sounds.
    usage: /<command> <category>
    aliases: [st]
  storage:
    description: Virtual storage for VIP members.
    usage: /<command> <category>
    aliases: [chests, chest]
  furnace:
    description: Virtual furnace for VIP members.
    usage: /<command> <category>
    aliases: [furnaces, smelt, cook]
  enchant:
    description: Virtual enchanting for VIP members.
    usage: /<command> <category>
    aliases: [enchanting]
  disposal:
    description: Virtual item disposal.
    usage: /<command> <category>
    aliases: [dispose,clear]